# Generated by Django 4.2 on 2023-05-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicmodel',
            name='time',
        ),
    ]
