# Generated by Django 4.2 on 2023-05-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_musicmodel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicmodel',
            name='playlist',
        ),
        migrations.AddField(
            model_name='musicmodel',
            name='playlist',
            field=models.ManyToManyField(null=True, related_name='used_music', to='music.playlistmodel'),
        ),
    ]
