# Generated by Django 4.2 on 2023-04-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_remove_approachmodel_break_after_approach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approachmodel',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='break_after_exercise',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='break_between_approaches',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutmodel',
            name='initial_break',
            field=models.IntegerField(),
        ),
    ]
