# Generated by Django 4.2 on 2023-04-30 08:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0004_alter_workoutmodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approachmodel',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approaches', to='workout.exercisemodel'),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.workoutmodel'),
        ),
        migrations.AlterField(
            model_name='workoutmodel',
            name='color',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Строка должна соответствовать значению цвета в HEX', regex='[0-9A-Fa-f]{6}')]),
        ),
        migrations.AlterUniqueTogether(
            name='workoutmodel',
            unique_together={('color', 'user')},
        ),
    ]
