# Generated by Django 4.2 on 2023-04-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_approachmodel_exercise_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='approachmodel',
            table='workout__approach',
        ),
        migrations.AlterModelTable(
            name='exercisemodel',
            table='workout__exercise',
        ),
        migrations.AlterModelTable(
            name='workoutmodel',
            table='workout__workout',
        ),
    ]
