# Generated by Django 4.2 on 2023-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_alter_approachmodel_table_alter_exercisemodel_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisemodel',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
