# Generated by Django 4.2 on 2023-05-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_alter_approachmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='number',
            field=models.IntegerField(default=1000),
        ),
    ]
